<?php
$entrystate='unpublished';
$platforms=array();
$genretags=array();
$gametitle='GG';
$descriptiontext="GG'ness";
$reviewvideourl=array('www.test.co.za','www.lol.com');
$instructionalvideourl=array('https://youtu.be/j3sPW0uIgs8');
$reviewtext=array('https://youtu.be/j3sPW0uIgs8');
$webguidelink=array('https://youtu.be/j3sPW0uIgs8');
$toollinks=array('https://youtu.be/j3sPW0uIgs8');
$sellers=array();
$company=array();
?>